[static]
vstatic = "/static/"
lstatic = "./public"
compress = "./settings/compress.json"

[database]
type="sqlite3"
uri = "./resource/db/lottery.2.sqlite3"

[server]
port = ":9000"
host = ":9000"

[template]
 home = "./templates"
 ldelime = "{%"
 rdelime = "%}"
 charset = "UTF-8"
 reload = true
 
[defaultvars]
appname = "filesync Dashboard"
 
[admin]
passwd = "micro1867321"

[log]
path = "./.log"
format = "060102.log"
